version: '3'
services:
    web:
        build: .
        command: yarn start-client
        volumes:
            - .:/usr/app/
            - /usr/app/node_modules
        ports:
            - "3000:3000"
