version: '3'
services:
    server:
        build: server/
        command: yarn start
        volumes: 
            - ./server:/usr/app/server
        ports:
            - "5000:5000"
    client:
        build: .
        command: yarn start-client
        volumes:
            - .:/usr/app/
        network_mode: host
        depends_on: 
            - server
        # ports:
        #     - "3000:3000"
            # - "5000:5000"
